name: Tests

on:
  pull_request:
    branches:
      - "master"
      - "development"

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run tests with RSpec
        run: |
          bundle exec rspec
